url: https://soledrop.io

# Site settings
title: SoleDrop
email: support@soledrop.in
description: "SoleDrop is an ultra-fast climbing shoe resoler with 1 week turnaround time or your money back."

webrick:
  headers:
    Access-Control-Allow-Origin: "*"

# Team names, titles and social links
people:
- name: Adriano Caloiaro
  pic: 1
  position: Founder
  social:
    - title: twitter
      url: https://twitter.com/adriano.fyi
    - title: facebook
      url: https://facebook.com/adriano.fyi

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/soledrop
  - title: facebook
    url: http://facebook.com/soledrop

# Postal address (add as many lines as necessary)
address:
  - line: 408 E. 65th St.
  - line: New York, New York 10065

# Build settings
markdown: kramdown
permalink: pretty
